// Copyright (c) 2026 by C. Klukas.
// Licensed under the MIT License. See LICENSE for details.

// Paglet ABI v1 (planning/cpp-abi-v1.md): constants and the MessagePack
// documents exchanged between host and guest. Shared by the guest SDK
// (clang, wasm32) and the host (GCC 16), so it is written by hand on top of
// msgpack.hpp instead of being generated by reflection: guests cannot reflect.
// All documents are maps with string keys; decoders skip unknown keys.

#pragma once

#include <paglets/msgpack.hpp>

#include <cstdint>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace paglets::abi {

inline constexpr std::uint32_t version = 1;
// Compatible additions within v1 (planning/cpp-abi-v1.md, section 13):
// 1 adds lent capabilities, resource capabilities, `revoked`, the service
// map of self_info and derive paths.
inline constexpr std::uint32_t minor_version = 1;
inline constexpr std::string_view version_marker = "paglets_abi_v1";

// Error codes (section 9). Negative results of imports and handlers.
enum Error : std::int32_t {
    ok = 0,
    invalid_argument = -1,
    bad_handle = -2,
    denied = -3,
    expired = -4,
    quota = -5,
    too_large = -6,
    malformed = -7,
    not_found = -8,
    bad_state = -9,
    unsupported = -10,
    internal = -11,
    timeout = -12,
    unknown_message = -13,
    failed = -14,
    gone = -15,
    revoked = -16,  // v1.1
};

inline constexpr std::string_view error_name(std::int32_t code) {
    switch (code) {
        case ok: return "ok";
        case invalid_argument: return "invalid_argument";
        case bad_handle: return "bad_handle";
        case denied: return "denied";
        case expired: return "expired";
        case quota: return "quota";
        case too_large: return "too_large";
        case malformed: return "malformed";
        case not_found: return "not_found";
        case bad_state: return "bad_state";
        case unsupported: return "unsupported";
        case internal: return "internal";
        case timeout: return "timeout";
        case unknown_message: return "unknown_message";
        case failed: return "failed";
        case gone: return "gone";
        case revoked: return "revoked";
        default: return "error";
    }
}

// Handler results (section 3.1).
inline constexpr std::int32_t handled = 0;
inline constexpr std::int32_t not_handled = 1;

enum class EventKind : std::int32_t {
    created = 1,
    activated = 2,
    deactivating = 3,
    arrived = 4,
    cloned = 5,
    dispatching = 6,
    disposing = 7,
};

enum class MessageKind : std::int32_t { message = 0, request = 1, reply = 2, timer = 3 };

enum class LifecycleOp : std::int32_t { dispose = 1, deactivate = 2, clone = 3, dispatch = 4 };

enum class LogLevel : std::int32_t { debug = 0, info = 1, warning = 2, error = 3 };

enum class Clock : std::int32_t { wall = 0, monotonic = 1 };

inline constexpr std::int32_t self_handle = 1;
inline constexpr std::int32_t default_priority = 3;
inline constexpr std::int32_t max_priority = 7;
inline constexpr std::int64_t default_timeout_ms = 30000;
inline constexpr std::size_t max_name_length = 128;
inline constexpr std::size_t max_document_size = 1024 * 1024;
inline constexpr std::string_view reserved_prefix = "paglets.";

// Functions of the `paglets` import module (section 5.2).
inline constexpr std::string_view import_module = "paglets";
inline constexpr std::string_view system_import_module = "paglets_sys";
inline constexpr std::string_view import_names[] = {
    "log",         "self_info", "send",         "request",   "reply",     "cap_derive", "cap_drop",
    "cap_inspect", "cap_list",  "create_child", "lifecycle", "timer_set", "now",        "random",
};

// Exports every ABI v1 module must provide (section 3).
inline constexpr std::string_view required_exports[] = {
    "paglets_abi_v1", "paglets_alloc", "paglets_free", "paglets_on_event", "paglets_on_message", "memory",
};

inline bool valid_message_name(std::string_view name) {
    return !name.empty() && name.size() <= max_name_length;
}
inline bool reserved_message_name(std::string_view name) {
    return name.starts_with(reserved_prefix);
}

// ---------------------------------------------------------------------------
// Documents

// Outgoing message: send, request, reply, timer_set.
struct OutMessage {
    std::string name;
    std::vector<std::uint8_t> payload;
    std::vector<std::int32_t> caps;
    std::int32_t priority = default_priority;
    std::int64_t timeout_ms = default_timeout_ms;
    // v1.1: capabilities shown to a system paglet for this message only;
    // they stay with the sender.
    std::vector<std::int32_t> lend;
    // v1.1, send and reply only: return at once; a message that cannot be
    // delivered is reported later as `paglets.undelivered` (Undelivered).
    bool async = false;
};

// v1.1: payload of `paglets.undelivered`, the report of an asynchronous send
// or reply that failed.
inline constexpr std::string_view undelivered_message = "paglets.undelivered";
struct Undelivered {
    std::string name;         // of the message that was not delivered
    std::int32_t handle = 0;  // endpoint (send) or reply capability (reply)
    std::int32_t status = 0;  // the error send or reply would have returned
};

struct SenderRecord {
    std::string id;
    std::string owner;
    std::string trust;
    std::string module;
    std::string host;
};

// Argument of paglets_on_message.
struct Delivered {
    MessageKind kind = MessageKind::message;
    std::string name;
    std::vector<std::uint8_t> payload;
    std::vector<std::int32_t> caps;
    std::int32_t priority = default_priority;
    std::optional<SenderRecord> sender;
    std::optional<std::string> badge;
    std::int32_t reply = 0;
    std::uint64_t correlation = 0;
    std::int32_t status = 0;
};

struct SelfInfo {
    std::string id;
    std::string module;
    std::string owner;
    std::string trust;
    std::string host;
    std::uint32_t abi = version;
    std::uint32_t minor = 0;  // v1.1: minor version of the host
    // v1.1: endpoints to system services the host installed, by service name.
    std::vector<std::pair<std::string, std::int32_t>> services;
};

struct DeriveSpec {
    std::optional<std::vector<std::string>> ops;
    std::optional<std::int64_t> expires_ms;
    std::optional<std::int64_t> uses;
    std::optional<bool> transferable;
    std::optional<std::string> badge;
    // v1.1: `dir` capabilities only: a relative path below the directory.
    std::optional<std::string> path;
};

struct CapInfo {
    std::string kind;
    std::string target;
    std::vector<std::string> ops;
    bool transferable = false;
    std::optional<std::string> badge;
    std::optional<std::int64_t> expires;  // Unix milliseconds
    std::optional<std::int64_t> uses_left;
    bool revoked = false;  // v1.1
};

struct ChildSpec {
    std::optional<std::string> module;  // hex hash; default: the creator's module
    std::vector<std::uint8_t> args;
    std::vector<std::int32_t> caps;
};

// Event documents. `created` and `cloned` share the args/caps fields.
struct StartEvent {
    std::vector<std::uint8_t> args;
    std::vector<std::int32_t> caps;
    std::optional<std::string> original;  // cloned only
};

struct ArrivedEvent {
    std::string from;
    std::vector<std::string> lost;
};

struct DispatchingEvent {
    std::string destination;
};

// Lifecycle arguments.
struct DeactivateArg {
    std::optional<std::int64_t> wake_after_ms;
};

struct CloneArg {
    std::vector<std::uint8_t> args;
    std::vector<std::int32_t> caps;
};

struct DispatchArg {
    std::string destination;
};

// ---------------------------------------------------------------------------
// Encoding helpers

namespace detail {

// Writes key/value pairs of a map whose size is known after counting.
template <class T>
void put(msgpack::Writer& w, std::string_view key, const T& value) {
    w.write_str(key);
    msgpack::write_value(w, value);
}

template <class T>
std::size_t present(const std::optional<T>& v) {
    return v ? 1 : 0;
}

template <class T>
void put_opt(msgpack::Writer& w, std::string_view key, const std::optional<T>& value) {
    if (value) put(w, key, *value);
}

// Reads a map, calling field(key, reader) for every key; field returns
// false on a type error and true otherwise (it skips keys it does not know).
template <class F>
bool read_map(msgpack::Reader& r, F&& field) {
    std::uint32_t n = 0;
    if (!r.read_map_header(n)) return false;
    for (std::uint32_t i = 0; i < n; ++i) {
        std::string_view key;
        if (!r.read_str(key)) return false;
        if (!field(key)) return false;
    }
    return r.ok();
}

}  // namespace detail

inline void paglets_encode(msgpack::Writer& w, const OutMessage& m) {
    w.write_map_header(5 + (m.lend.empty() ? 0 : 1) + (m.async ? 1 : 0));
    detail::put(w, "name", m.name);
    detail::put(w, "payload", m.payload);
    detail::put(w, "caps", m.caps);
    detail::put(w, "priority", m.priority);
    detail::put(w, "timeout_ms", m.timeout_ms);
    if (!m.lend.empty()) detail::put(w, "lend", m.lend);
    if (m.async) detail::put(w, "async", m.async);
}

inline void paglets_encode(msgpack::Writer& w, const Undelivered& u) {
    w.write_map_header(3);
    detail::put(w, "name", u.name);
    detail::put(w, "handle", u.handle);
    detail::put(w, "status", u.status);
}

inline bool paglets_decode(msgpack::Reader& r, Undelivered& u) {
    return detail::read_map(r, [&](std::string_view k) {
        if (k == "name") return msgpack::read_value(r, u.name);
        if (k == "handle") return msgpack::read_value(r, u.handle);
        if (k == "status") return msgpack::read_value(r, u.status);
        return r.skip();
    });
}

inline bool paglets_decode(msgpack::Reader& r, OutMessage& m) {
    return detail::read_map(r, [&](std::string_view k) {
        if (k == "name") return msgpack::read_value(r, m.name);
        if (k == "payload") return msgpack::read_value(r, m.payload);
        if (k == "caps") return msgpack::read_value(r, m.caps);
        if (k == "priority") return msgpack::read_value(r, m.priority);
        if (k == "timeout_ms") return msgpack::read_value(r, m.timeout_ms);
        if (k == "lend") return msgpack::read_value(r, m.lend);
        if (k == "async") return msgpack::read_value(r, m.async);
        return r.skip();
    });
}

inline void paglets_encode(msgpack::Writer& w, const SenderRecord& s) {
    w.write_map_header(5);
    detail::put(w, "id", s.id);
    detail::put(w, "owner", s.owner);
    detail::put(w, "trust", s.trust);
    detail::put(w, "module", s.module);
    detail::put(w, "host", s.host);
}

inline bool paglets_decode(msgpack::Reader& r, SenderRecord& s) {
    return detail::read_map(r, [&](std::string_view k) {
        if (k == "id") return msgpack::read_value(r, s.id);
        if (k == "owner") return msgpack::read_value(r, s.owner);
        if (k == "trust") return msgpack::read_value(r, s.trust);
        if (k == "module") return msgpack::read_value(r, s.module);
        if (k == "host") return msgpack::read_value(r, s.host);
        return r.skip();
    });
}

inline void paglets_encode(msgpack::Writer& w, const Delivered& d) {
    const bool is_request = d.kind == MessageKind::request;
    const bool is_reply = d.kind == MessageKind::reply;
    w.write_map_header(5 + detail::present(d.sender) + detail::present(d.badge) + (is_request ? 1 : 0) +
                       (is_reply ? 2 : 0));
    detail::put(w, "kind", static_cast<std::int32_t>(d.kind));
    detail::put(w, "name", d.name);
    detail::put(w, "payload", d.payload);
    detail::put(w, "caps", d.caps);
    detail::put(w, "priority", d.priority);
    detail::put_opt(w, "sender", d.sender);
    detail::put_opt(w, "badge", d.badge);
    if (is_request) detail::put(w, "reply", d.reply);
    if (is_reply) {
        detail::put(w, "correlation", d.correlation);
        detail::put(w, "status", d.status);
    }
}

inline bool paglets_decode(msgpack::Reader& r, Delivered& d) {
    return detail::read_map(r, [&](std::string_view k) {
        if (k == "kind") {
            std::int32_t kind = 0;
            if (!msgpack::read_value(r, kind) || kind < 0 || kind > 3) return false;
            d.kind = static_cast<MessageKind>(kind);
            return true;
        }
        if (k == "name") return msgpack::read_value(r, d.name);
        if (k == "payload") return msgpack::read_value(r, d.payload);
        if (k == "caps") return msgpack::read_value(r, d.caps);
        if (k == "priority") return msgpack::read_value(r, d.priority);
        if (k == "sender") return msgpack::read_value(r, d.sender);
        if (k == "badge") return msgpack::read_value(r, d.badge);
        if (k == "reply") return msgpack::read_value(r, d.reply);
        if (k == "correlation") return msgpack::read_value(r, d.correlation);
        if (k == "status") return msgpack::read_value(r, d.status);
        return r.skip();
    });
}

inline void paglets_encode(msgpack::Writer& w, const SelfInfo& s) {
    w.write_map_header(8);
    detail::put(w, "id", s.id);
    detail::put(w, "module", s.module);
    detail::put(w, "owner", s.owner);
    detail::put(w, "trust", s.trust);
    detail::put(w, "host", s.host);
    detail::put(w, "abi", s.abi);
    detail::put(w, "minor", s.minor);
    w.write_str("services");
    w.write_map_header(s.services.size());
    for (const auto& [name, handle] : s.services) {
        w.write_str(name);
        w.write_int(handle);
    }
}

inline bool paglets_decode(msgpack::Reader& r, SelfInfo& s) {
    return detail::read_map(r, [&](std::string_view k) {
        if (k == "id") return msgpack::read_value(r, s.id);
        if (k == "module") return msgpack::read_value(r, s.module);
        if (k == "owner") return msgpack::read_value(r, s.owner);
        if (k == "trust") return msgpack::read_value(r, s.trust);
        if (k == "host") return msgpack::read_value(r, s.host);
        if (k == "abi") return msgpack::read_value(r, s.abi);
        if (k == "minor") return msgpack::read_value(r, s.minor);
        if (k == "services") {
            std::uint32_t n = 0;
            if (!r.read_map_header(n)) return false;
            s.services.clear();
            for (std::uint32_t i = 0; i < n; ++i) {
                std::string name;
                std::int32_t handle = 0;
                if (!msgpack::read_value(r, name) || !msgpack::read_value(r, handle)) return false;
                s.services.emplace_back(std::move(name), handle);
            }
            return true;
        }
        return r.skip();
    });
}

inline void paglets_encode(msgpack::Writer& w, const DeriveSpec& s) {
    w.write_map_header(detail::present(s.ops) + detail::present(s.expires_ms) + detail::present(s.uses) +
                       detail::present(s.transferable) + detail::present(s.badge) + detail::present(s.path));
    detail::put_opt(w, "ops", s.ops);
    detail::put_opt(w, "expires_ms", s.expires_ms);
    detail::put_opt(w, "uses", s.uses);
    detail::put_opt(w, "transferable", s.transferable);
    detail::put_opt(w, "badge", s.badge);
    detail::put_opt(w, "path", s.path);
}

inline bool paglets_decode(msgpack::Reader& r, DeriveSpec& s) {
    return detail::read_map(r, [&](std::string_view k) {
        if (k == "ops") return msgpack::read_value(r, s.ops);
        if (k == "expires_ms") return msgpack::read_value(r, s.expires_ms);
        if (k == "uses") return msgpack::read_value(r, s.uses);
        if (k == "transferable") return msgpack::read_value(r, s.transferable);
        if (k == "badge") return msgpack::read_value(r, s.badge);
        if (k == "path") return msgpack::read_value(r, s.path);
        return r.skip();
    });
}

inline void paglets_encode(msgpack::Writer& w, const CapInfo& c) {
    w.write_map_header(4 + detail::present(c.badge) + detail::present(c.expires) + detail::present(c.uses_left) +
                       (c.revoked ? 1 : 0));
    detail::put(w, "kind", c.kind);
    detail::put(w, "target", c.target);
    detail::put(w, "ops", c.ops);
    detail::put(w, "transferable", c.transferable);
    detail::put_opt(w, "badge", c.badge);
    detail::put_opt(w, "expires", c.expires);
    detail::put_opt(w, "uses_left", c.uses_left);
    if (c.revoked) detail::put(w, "revoked", c.revoked);
}

inline bool paglets_decode(msgpack::Reader& r, CapInfo& c) {
    return detail::read_map(r, [&](std::string_view k) {
        if (k == "kind") return msgpack::read_value(r, c.kind);
        if (k == "target") return msgpack::read_value(r, c.target);
        if (k == "ops") return msgpack::read_value(r, c.ops);
        if (k == "transferable") return msgpack::read_value(r, c.transferable);
        if (k == "badge") return msgpack::read_value(r, c.badge);
        if (k == "expires") return msgpack::read_value(r, c.expires);
        if (k == "uses_left") return msgpack::read_value(r, c.uses_left);
        if (k == "revoked") return msgpack::read_value(r, c.revoked);
        return r.skip();
    });
}

inline void paglets_encode(msgpack::Writer& w, const ChildSpec& s) {
    w.write_map_header(2 + detail::present(s.module));
    detail::put_opt(w, "module", s.module);
    detail::put(w, "args", s.args);
    detail::put(w, "caps", s.caps);
}

inline bool paglets_decode(msgpack::Reader& r, ChildSpec& s) {
    return detail::read_map(r, [&](std::string_view k) {
        if (k == "module") return msgpack::read_value(r, s.module);
        if (k == "args") return msgpack::read_value(r, s.args);
        if (k == "caps") return msgpack::read_value(r, s.caps);
        return r.skip();
    });
}

inline void paglets_encode(msgpack::Writer& w, const StartEvent& e) {
    w.write_map_header(2 + detail::present(e.original));
    detail::put(w, "args", e.args);
    detail::put(w, "caps", e.caps);
    detail::put_opt(w, "original", e.original);
}

inline bool paglets_decode(msgpack::Reader& r, StartEvent& e) {
    return detail::read_map(r, [&](std::string_view k) {
        if (k == "args") return msgpack::read_value(r, e.args);
        if (k == "caps") return msgpack::read_value(r, e.caps);
        if (k == "original") return msgpack::read_value(r, e.original);
        return r.skip();
    });
}

inline void paglets_encode(msgpack::Writer& w, const ArrivedEvent& e) {
    w.write_map_header(2);
    detail::put(w, "from", e.from);
    detail::put(w, "lost", e.lost);
}

inline bool paglets_decode(msgpack::Reader& r, ArrivedEvent& e) {
    return detail::read_map(r, [&](std::string_view k) {
        if (k == "from") return msgpack::read_value(r, e.from);
        if (k == "lost") return msgpack::read_value(r, e.lost);
        return r.skip();
    });
}

inline void paglets_encode(msgpack::Writer& w, const DispatchingEvent& e) {
    w.write_map_header(1);
    detail::put(w, "destination", e.destination);
}

inline bool paglets_decode(msgpack::Reader& r, DispatchingEvent& e) {
    return detail::read_map(r, [&](std::string_view k) {
        if (k == "destination") return msgpack::read_value(r, e.destination);
        return r.skip();
    });
}

inline void paglets_encode(msgpack::Writer& w, const DeactivateArg& a) {
    w.write_map_header(detail::present(a.wake_after_ms));
    detail::put_opt(w, "wake_after_ms", a.wake_after_ms);
}

inline bool paglets_decode(msgpack::Reader& r, DeactivateArg& a) {
    return detail::read_map(r, [&](std::string_view k) {
        if (k == "wake_after_ms") return msgpack::read_value(r, a.wake_after_ms);
        return r.skip();
    });
}

inline void paglets_encode(msgpack::Writer& w, const CloneArg& a) {
    w.write_map_header(2);
    detail::put(w, "args", a.args);
    detail::put(w, "caps", a.caps);
}

inline bool paglets_decode(msgpack::Reader& r, CloneArg& a) {
    return detail::read_map(r, [&](std::string_view k) {
        if (k == "args") return msgpack::read_value(r, a.args);
        if (k == "caps") return msgpack::read_value(r, a.caps);
        return r.skip();
    });
}

inline void paglets_encode(msgpack::Writer& w, const DispatchArg& a) {
    w.write_map_header(1);
    detail::put(w, "destination", a.destination);
}

inline bool paglets_decode(msgpack::Reader& r, DispatchArg& a) {
    return detail::read_map(r, [&](std::string_view k) {
        if (k == "destination") return msgpack::read_value(r, a.destination);
        return r.skip();
    });
}

// ---------------------------------------------------------------------------
// Whole-document helpers

template <class T>
std::vector<std::uint8_t> encode(const T& value) {
    msgpack::Writer w;
    msgpack::write_value(w, value);
    return w.take();
}

// Decodes a complete document; trailing bytes make it malformed.
template <class T>
bool decode(std::span<const std::uint8_t> bytes, T& value) {
    msgpack::Reader r(bytes);
    return msgpack::read_value(r, value) && r.ok() && r.at_end();
}

}  // namespace paglets::abi
