// Copyright (c) 2026 by C. Klukas.
// Licensed under the MIT License. See LICENSE for details.

// Guest SDK for paglets (paglet ABI v1, planning/cpp-abi-v1.md), compiled to
// wasm32-wasip1 by clang.
//
// A paglet derives from paglets::Paglet, registers message handlers on its
// router and is made known to the SDK with PAGLETS_PAGLET(Type):
//
//     struct Hello : paglets::Paglet {
//         Hello() {
//             router().on("greet", [](paglets::Message& m) {
//                 m.reply(std::string("hello"));
//             });
//         }
//     };
//     PAGLETS_PAGLET(Hello)
//
// The paglet object and everything it owns live in linear memory, so memory
// images move them without serialization code. Message bodies are encoded
// with paglets::msgpack; types generated by schema_gen plug in through
// paglets_encode / paglets_decode.

#pragma once

#include <paglets/abi.hpp>
#include <paglets/msgpack.hpp>

#include <cstdint>
#include <expected>
#include <functional>
#include <map>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace paglets {

using Bytes = std::vector<std::uint8_t>;

// Results carry an ABI error code (abi::Error) on failure.
template <class T>
using Result = std::expected<T, std::int32_t>;

template <class T>
Bytes encode(const T& value) {
    msgpack::Writer w;
    msgpack::write_value(w, value);
    return w.take();
}

template <class T>
bool decode(std::span<const std::uint8_t> bytes, T& value) {
    msgpack::Reader r(bytes);
    return msgpack::read_value(r, value) && r.ok() && r.at_end();
}

// ---------------------------------------------------------------------------
// Logging, clocks, random

void log(abi::LogLevel level, std::string_view text);
inline void log(std::string_view text) {
    log(abi::LogLevel::info, text);
}

std::int64_t now_ns(abi::Clock clock = abi::Clock::wall);
void random_bytes(std::span<std::uint8_t> out);

// ---------------------------------------------------------------------------
// Capabilities

class Capability {
public:
    Capability() = default;
    explicit Capability(std::int32_t handle) : handle_(handle) {}

    std::int32_t handle() const { return handle_; }
    explicit operator bool() const { return handle_ > 0; }

    Result<abi::CapInfo> inspect() const;
    // Derives a weaker copy; rights can only shrink.
    Result<Capability> derive(const abi::DeriveSpec& spec) const;
    // Releases the capability (cancels a timer, answers `gone` for a reply).
    Result<void> drop();

    // Marks the handle as given away (after a transfer).
    std::int32_t release() { return std::exchange(handle_, 0); }

private:
    std::int32_t handle_ = 0;
};

class Message;
using ReplyHandler = std::function<void(Message& reply)>;

struct SendOptions {
    std::int32_t priority = abi::default_priority;
    std::vector<Capability> caps;  // transferred: the handles become invalid on success
    std::vector<Capability> lend;  // shown to a system paglet for this message; they stay valid
    // Return at once; if the message cannot be delivered, Paglet::on_undelivered
    // runs later with the error (ABI v1.1). Transferred handles are given up.
    bool async = false;
};

struct RequestOptions {
    std::int32_t priority = abi::default_priority;
    std::vector<Capability> caps;
    std::int64_t timeout_ms = abi::default_timeout_ms;
    std::vector<Capability> lend;
};

// A capability to send messages to a paglet or service.
class Endpoint : public Capability {
public:
    Endpoint() = default;
    explicit Endpoint(std::int32_t handle) : Capability(handle) {}
    explicit Endpoint(const Capability& c) : Capability(c.handle()) {}

    Result<void> send_raw(std::string_view name, Bytes payload, SendOptions options = {}) const;
    Result<void> send(std::string_view name, SendOptions options = {}) const {
        return send_raw(name, {}, std::move(options));
    }
    template <class T>
    Result<void> send(std::string_view name, const T& body, SendOptions options = {}) const {
        return send_raw(name, encode(body), std::move(options));
    }

    // Sends a request; `on_reply` runs in a later handler with the reply
    // (status 0) or a failure status (timeout, unknown_message, failed, gone).
    // Returns the correlation ID.
    Result<std::uint64_t> request_raw(std::string_view name, Bytes payload, ReplyHandler on_reply,
                                      RequestOptions options = {}) const;
    template <class T>
    Result<std::uint64_t> request(std::string_view name, const T& body, ReplyHandler on_reply,
                                  RequestOptions options = {}) const {
        return request_raw(name, encode(body), std::move(on_reply), std::move(options));
    }
    Result<std::uint64_t> request(std::string_view name, ReplyHandler on_reply, RequestOptions options = {}) const {
        return request_raw(name, {}, std::move(on_reply), std::move(options));
    }
};

// The paglet's own endpoint (handle 1).
inline Endpoint self() {
    return Endpoint(abi::self_handle);
}

// The endpoint to a system service the host installed (for example
// "directory" or "storage"); not_found if there is none.
Result<Endpoint> service(std::string_view name);

Result<abi::SelfInfo> self_info();
Result<std::vector<Capability>> list_caps();

// ---------------------------------------------------------------------------
// Messages

class Message {
public:
    explicit Message(abi::Delivered d) : d_(std::move(d)) {}

    abi::MessageKind kind() const { return d_.kind; }
    bool is_request() const { return d_.kind == abi::MessageKind::request; }
    bool is_reply() const { return d_.kind == abi::MessageKind::reply; }
    const std::string& name() const { return d_.name; }
    std::span<const std::uint8_t> payload() const { return d_.payload; }
    std::int32_t priority() const { return d_.priority; }
    const std::optional<abi::SenderRecord>& sender() const { return d_.sender; }
    const std::optional<std::string>& badge() const { return d_.badge; }

    // Replies: 0 for a real reply, otherwise an abi::Error status.
    std::int32_t status() const { return d_.status; }
    bool ok() const { return d_.status == 0; }
    std::uint64_t correlation() const { return d_.correlation; }

    template <class T>
    bool decode(T& out) const {
        return paglets::decode(d_.payload, out);
    }

    // Capabilities transferred with the message. take_cap moves one out.
    std::size_t cap_count() const { return d_.caps.size(); }
    Capability take_cap(std::size_t index);

    // Answers a request (once). `async`: return at once; a failure reaches
    // Paglet::on_undelivered later.
    Result<void> reply_raw(Bytes payload, std::vector<Capability> caps = {}, bool async = false);
    Result<void> reply() { return reply_raw({}); }
    template <class T>
    Result<void> reply(const T& body, std::vector<Capability> caps = {}) {
        return reply_raw(encode(body), std::move(caps));
    }
    template <class T>
    Result<void> reply_async(const T& body, std::vector<Capability> caps = {}) {
        return reply_raw(encode(body), std::move(caps), true);
    }
    bool replied() const { return replied_; }

    // Keeps the reply capability for an answer from a later handler. Without
    // it, a request that was handled but not answered is answered `gone`.
    Capability defer_reply();

    // True for a request that was neither answered nor deferred.
    bool reply_pending() const { return is_request() && !replied_ && !deferred_ && d_.reply > 0; }
    std::int32_t reply_handle() const { return d_.reply; }

private:
    abi::Delivered d_;
    bool replied_ = false;
    bool deferred_ = false;
};

// Answers a deferred request.
Result<void> reply_to(Capability& reply, Bytes payload, std::vector<Capability> caps = {}, bool async = false);
template <class T>
Result<void> reply_to(Capability& reply, const T& body, std::vector<Capability> caps = {}) {
    return reply_to(reply, encode(body), std::move(caps));
}

// ---------------------------------------------------------------------------
// Routing

class Router {
public:
    using Handler = std::function<std::int32_t(Message&)>;

    // Handler without a typed body: void(Message&) or int32_t(Message&).
    template <class F>
    void on(std::string name, F&& f) {
        handlers_[std::move(name)] = wrap(std::forward<F>(f));
    }

    // Handler with a typed body: void(const T&, Message&) or int32_t(const T&, Message&).
    // A body that does not decode is answered `malformed`.
    template <class T, class F>
    void on(std::string name, F&& f) {
        handlers_[std::move(name)] = [g = std::forward<F>(f)](Message& m) -> std::int32_t {
            T body{};
            if (!m.decode(body)) return abi::malformed;
            if constexpr (std::is_same_v<std::invoke_result_t<decltype(g)&, const T&, Message&>, void>) {
                g(body, m);
                return abi::handled;
            } else {
                return g(body, m);
            }
        };
    }

    // Called for names without a handler (default: not handled).
    template <class F>
    void otherwise(F&& f) {
        fallback_ = wrap(std::forward<F>(f));
    }

    std::int32_t dispatch(Message& m) const;

private:
    template <class F>
    static Handler wrap(F&& f) {
        return [g = std::forward<F>(f)](Message& m) -> std::int32_t {
            if constexpr (std::is_same_v<std::invoke_result_t<decltype(g)&, Message&>, void>) {
                g(m);
                return abi::handled;
            } else {
                return g(m);
            }
        };
    }

    std::map<std::string, Handler, std::less<>> handlers_;
    Handler fallback_;
};

// ---------------------------------------------------------------------------
// The paglet

struct Started {
    Bytes args;
    std::vector<Capability> caps;
    std::optional<std::string> original;  // set for clones

    template <class T>
    bool decode_args(T& out) const {
        return paglets::decode(args, out);
    }
};

class Paglet {
public:
    virtual ~Paglet() = default;

    virtual void on_created(Started&) {}
    virtual void on_cloned(Started&) {}
    virtual void on_activated() {}
    virtual void on_deactivating() {}
    virtual void on_arrived(const abi::ArrivedEvent&) {}
    virtual void on_dispatching(const abi::DispatchingEvent&) {}
    virtual void on_disposing() {}
    // An asynchronous send or reply could not be delivered (default: logged).
    virtual void on_undelivered(const abi::Undelivered& u);
    // A dispatch, or a clone for another host, did not happen (default:
    // logged). After a failed dispatch the paglet continues here.
    virtual void on_move_failed(const abi::MoveFailed& f);

    // Default: replies to own requests go to their continuation, everything
    // else to the router.
    virtual std::int32_t on_message(Message& m) { return router_.dispatch(m); }

    Router& router() { return router_; }

private:
    Router router_;
};

// ---------------------------------------------------------------------------
// Lifecycle, children, timers

// Creates a child paglet from `module` (hex hash; default: this module).
// The child gets exactly the capabilities passed in `caps`.
Result<Endpoint> create_child_raw(Bytes args, std::vector<Capability> caps = {},
                                  std::optional<std::string> module = std::nullopt);
template <class T>
Result<Endpoint> create_child(const T& args, std::vector<Capability> caps = {},
                              std::optional<std::string> module = std::nullopt) {
    return create_child_raw(encode(args), std::move(caps), std::move(module));
}

// The following take effect when the current handler returns.
Result<void> dispose();
Result<void> deactivate(std::optional<std::int64_t> wake_after_ms = std::nullopt);
// With a destination, the clone is made on another host (ABI v1.1; only
// endpoints can be passed then).
Result<Endpoint> clone_raw(Bytes args = {}, std::vector<Capability> caps = {},
                           std::optional<std::string> destination = std::nullopt);
Result<void> dispatch(std::string destination);

// Delivers the message to this paglet after `delay_ms`; drop the returned
// capability to cancel.
Result<Capability> after_raw(std::int64_t delay_ms, std::string_view name, Bytes payload = {},
                             std::int32_t priority = abi::default_priority);
template <class T>
Result<Capability> after(std::int64_t delay_ms, std::string_view name, const T& body,
                         std::int32_t priority = abi::default_priority) {
    return after_raw(delay_ms, name, encode(body), priority);
}

namespace detail {
Paglet& paglet();
}  // namespace detail

}  // namespace paglets

// Registers the paglet type. Exactly one per module.
#define PAGLETS_PAGLET(Type)    \
    namespace paglets::detail { \
    Paglet& paglet() {          \
        static Type instance;   \
        return instance;        \
    }                           \
    }
