# Copyright (c) 2026 by C. Klukas.
# Licensed under the MIT License. See LICENSE for details.
"""Built-in mesh compute-slot scheduler service."""

from .affinity import CpuAffinityResult, apply_current_process_cpu_affinity, apply_process_cpu_affinity
from .agent import (
    CANCEL_SLOT_REQUESTS,
    CANDIDATE_HOSTS,
    COMPUTE_SLOTS,
    COMPUTE_USAGE_PATHS_MESSAGE,
    RELEASE_SLOT,
    REQUEST_SLOT,
    SCHEDULER_STATUS,
    SYNC_SCHEDULER_STATUS,
    CancelSlotRequestsReply,
    CancelSlotRequestsRequest,
    CandidateHost,
    CandidateHostsReply,
    CandidateHostsRequest,
    ComputeJobRuntimeInfo,
    ComputeSlotRequest,
    ComputeSlotsAgent,
    ComputeSlotsState,
    SchedulerHostStatus,
    SchedulerStatusReply,
    SchedulerStatusRequest,
    SchedulerStatusSyncReply,
    SchedulerStatusSyncRequest,
    SlotDecisionReply,
    SlotLease,
    SlotReleaseReply,
    SlotReleaseRequest,
)
from .groups import (
    GROUP_STATUS_ACTIVE,
    GROUP_STATUS_COMPLETE,
    GROUP_STATUS_RETURNING_HOME,
    GROUP_STATUS_WAITING_FOR_HOME,
    CollectingComputeJobPaglet,
    CollectingComputeJobState,
    ComputeJobGroupSubmission,
    ResultCollectorPaglet,
    ResultCollectorState,
    submit_compute_job_group,
)
from .job import (
    COMPUTE_STATUS_COMPLETED,
    COMPUTE_STATUS_FAILED_FINAL,
    COMPUTE_STATUS_NEW,
    COMPUTE_STATUS_PLACING,
    COMPUTE_STATUS_RUNNING,
    COMPUTE_STATUS_WAITING_FOR_SLOT,
    ComputeJobPaglet,
    ComputeJobState,
)

__all__ = [
    "CANCEL_SLOT_REQUESTS",
    "CANDIDATE_HOSTS",
    "COMPUTE_SLOTS",
    "COMPUTE_STATUS_COMPLETED",
    "COMPUTE_STATUS_FAILED_FINAL",
    "COMPUTE_STATUS_NEW",
    "COMPUTE_STATUS_PLACING",
    "COMPUTE_STATUS_RUNNING",
    "COMPUTE_STATUS_WAITING_FOR_SLOT",
    "COMPUTE_USAGE_PATHS_MESSAGE",
    "GROUP_STATUS_ACTIVE",
    "GROUP_STATUS_COMPLETE",
    "GROUP_STATUS_RETURNING_HOME",
    "GROUP_STATUS_WAITING_FOR_HOME",
    "RELEASE_SLOT",
    "REQUEST_SLOT",
    "SCHEDULER_STATUS",
    "SYNC_SCHEDULER_STATUS",
    "CancelSlotRequestsReply",
    "CancelSlotRequestsRequest",
    "CandidateHost",
    "CandidateHostsReply",
    "CandidateHostsRequest",
    "CollectingComputeJobPaglet",
    "CollectingComputeJobState",
    "ComputeJobGroupSubmission",
    "ComputeJobPaglet",
    "ComputeJobRuntimeInfo",
    "ComputeJobState",
    "ComputeSlotRequest",
    "ComputeSlotsAgent",
    "ComputeSlotsState",
    "CpuAffinityResult",
    "ResultCollectorPaglet",
    "ResultCollectorState",
    "SchedulerHostStatus",
    "SchedulerStatusReply",
    "SchedulerStatusRequest",
    "SchedulerStatusSyncReply",
    "SchedulerStatusSyncRequest",
    "SlotDecisionReply",
    "SlotLease",
    "SlotReleaseReply",
    "SlotReleaseRequest",
    "apply_current_process_cpu_affinity",
    "apply_process_cpu_affinity",
    "submit_compute_job_group",
]
