# Copyright (c) 2026 by C. Klukas.
# Licensed under the MIT License. See LICENSE for details.

"""Keep the generated parts of the Markdown documentation in sync with the code.

The documentation site is built by ckdocs, which renders the Markdown files
tracked in Git as they are. Two kinds of content are therefore generated into
the Markdown files themselves, between HTML comment markers that ckdocs drops:

``<!-- snippet: PATH[:SECTION] | LABEL -->`` ... ``<!-- /snippet -->``
    A source link and a fenced code block with the lines between
    ``--8<-- [start:SECTION]`` and ``--8<-- [end:SECTION]`` in PATH, or the
    whole file when no section is given.

``<!-- api: MODULE -->`` ... ``<!-- /api -->``
    API reference for MODULE: its docstring and the documented public classes,
    functions, methods, properties, dataclass fields, and enum members.

Usage from the repository root::

    uv run python tools/docs_sync.py          # rewrite the generated sections
    uv run python tools/docs_sync.py --check  # fail if any section is stale
"""

from __future__ import annotations

import argparse
import dataclasses
import enum
import importlib
import inspect
import re
import sys
import textwrap
from collections.abc import Callable
from pathlib import Path
from typing import Any

REPOSITORY_URL = "https://github.com/cklukas/paglets/blob/main"

MARKER = re.compile(
    r"(?P<open><!-- (?P<kind>snippet|api): (?P<arg>[^>]*?) -->\n)(?P<body>.*?)(?P<close><!-- /(?P=kind) -->)",
    re.S,
)
SECTION_START = "--8<-- [start:{}]"
SECTION_END = "--8<-- [end:{}]"
LANGUAGES = {".py": "python", ".toml": "toml", ".json": "json", ".sh": "bash", ".yml": "yaml", ".yaml": "yaml"}


class DocsSyncError(Exception):
    """A marker names a file, section, or module that does not exist."""


# ---------------------------------------------------------------------------
# Snippets


def render_snippet(root: Path, argument: str) -> str:
    """Render the source link and code block for one snippet marker."""
    target, _, label = (part.strip() for part in argument.partition("|"))
    path_text, _, section = target.partition(":")
    path = root / path_text
    if not path_text or not path.is_file():
        raise DocsSyncError(f"snippet source not found: {path_text!r}")

    lines = path.read_text(encoding="utf-8").splitlines()
    if section:
        start = next((i for i, line in enumerate(lines) if SECTION_START.format(section) in line), None)
        end = next((i for i, line in enumerate(lines) if SECTION_END.format(section) in line), None)
        if start is None or end is None or end <= start:
            raise DocsSyncError(f"section {section!r} not found in {path_text}")
        lines = lines[start + 1 : end]
    code = textwrap.dedent("\n".join(lines)).strip("\n")
    language = LANGUAGES.get(path.suffix, "")
    label = label or (f"{section} in {path.name}" if section else path_text)
    return f"Source: [{label}]({REPOSITORY_URL}/{path_text})\n\n```{language}\n{code}\n```\n"


# ---------------------------------------------------------------------------
# API reference


def _source_line(obj: Any) -> int:
    try:
        return inspect.getsourcelines(obj)[1]
    except (OSError, TypeError):
        return 0


def _own_docstring(obj: Any) -> str | None:
    doc = obj.__doc__ if isinstance(obj.__doc__, str) else None
    if doc is None:
        return None
    if inspect.isclass(obj) and dataclasses.is_dataclass(obj) and doc.startswith(f"{obj.__name__}("):
        return None  # docstring generated by @dataclass, not written by hand
    text = inspect.cleandoc(doc)
    return text or None


def _format_default(value: Any) -> str:
    if isinstance(value, enum.Enum):
        return f"{type(value).__name__}.{value.name}"
    text = repr(value)
    text = re.sub(r" at 0x[0-9a-fA-F]+", "", text)
    return text if len(text) <= 60 else text[:57] + "..."


def _format_annotation(annotation: Any) -> str:
    if isinstance(annotation, str):
        return annotation
    return inspect.formatannotation(annotation)


def format_signature(name: str, function: Callable[..., Any], *, skip_first: bool = False) -> str:
    """Return a Python signature line, using annotation text as written in the source."""
    try:
        signature = inspect.signature(function)
    except (TypeError, ValueError):
        return f"def {name}(...)"
    parameters = list(signature.parameters.values())
    if skip_first and parameters and parameters[0].name in {"self", "cls"}:
        parameters = parameters[1:]

    parts: list[str] = []
    positional_only_done = False
    keyword_only_marked = False
    for index, parameter in enumerate(parameters):
        kind = parameter.kind
        if kind is inspect.Parameter.KEYWORD_ONLY and not keyword_only_marked:
            parts.append("*")
            keyword_only_marked = True
        text = parameter.name
        if kind is inspect.Parameter.VAR_POSITIONAL:
            text = "*" + text
            keyword_only_marked = True
        elif kind is inspect.Parameter.VAR_KEYWORD:
            text = "**" + text
        if parameter.annotation is not inspect.Parameter.empty:
            text += ": " + _format_annotation(parameter.annotation)
        if parameter.default is not inspect.Parameter.empty:
            separator = " = " if parameter.annotation is not inspect.Parameter.empty else "="
            text += separator + _format_default(parameter.default)
        parts.append(text)
        next_kind = parameters[index + 1].kind if index + 1 < len(parameters) else None
        if (
            kind is inspect.Parameter.POSITIONAL_ONLY
            and next_kind is not inspect.Parameter.POSITIONAL_ONLY
            and not positional_only_done
        ):
            parts.append("/")
            positional_only_done = True

    returns = ""
    if signature.return_annotation is not inspect.Signature.empty:
        returns = " -> " + _format_annotation(signature.return_annotation)
    prefix = "async def" if inspect.iscoroutinefunction(function) else "def"
    one_line = f"{prefix} {name}({', '.join(parts)}){returns}"
    if len(one_line) <= 100:
        return one_line
    inner = "".join(f"    {part},\n" for part in parts)
    return f"{prefix} {name}(\n{inner}){returns}"


def _code(text: str) -> str:
    return f"```python\n{text}\n```\n"


def _table_cell(text: str) -> str:
    # Cells are code spans; ckdocs keeps "|" inside a code span as text (and,
    # unlike GitHub, would show a backslash escape literally).
    return text.replace("\n", " ")


def _dataclass_fields(cls: type) -> str:
    rows = []
    for field in dataclasses.fields(cls):
        if field.name.startswith("_"):
            continue
        if field.default is not dataclasses.MISSING:
            default = f"`{_format_default(field.default)}`"
        elif field.default_factory is not dataclasses.MISSING:
            factory = getattr(field.default_factory, "__name__", "")
            default = f"`{factory}()`" if factory.isidentifier() else "computed"
        else:
            default = "required"
        annotation = _format_annotation(field.type)
        rows.append(f"| `{field.name}` | `{_table_cell(annotation)}` | {_table_cell(default)} |")
    if not rows:
        return ""
    return "| Field | Type | Default |\n|---|---|---|\n" + "\n".join(rows) + "\n"


def _enum_members(cls: type[enum.Enum]) -> str:
    rows = [f"| `{member.name}` | `{_table_cell(repr(member.value))}` |" for member in cls]
    if not rows:
        return ""
    return "| Member | Value |\n|---|---|\n" + "\n".join(rows) + "\n"


def _class_members(cls: type) -> list[tuple[int, str, Any]]:
    members = []
    for name, raw in vars(cls).items():
        if name.startswith("_"):
            continue
        target = raw
        if isinstance(raw, (staticmethod, classmethod)):
            target = raw.__func__
        if isinstance(raw, property):
            target = raw.fget
        if not (inspect.isfunction(target) or isinstance(raw, property)):
            continue
        if target is None or _own_docstring(target) is None:
            continue
        members.append((_source_line(target), name, raw))
    return sorted(members, key=lambda item: (item[0], item[1]))


def render_class(cls: type) -> str:
    """Render one documented class with its documented public members."""
    bases = [base.__name__ for base in cls.__bases__ if base is not object]
    head = f"class {cls.__name__}({', '.join(bases)})" if bases else f"class {cls.__name__}"
    out = [f"#### `{cls.__name__}`\n", _code(head), (_own_docstring(cls) or "") + "\n"]
    if isinstance(cls, type) and issubclass(cls, enum.Enum):
        members = _enum_members(cls)
        if members:
            out.append(members)
    elif dataclasses.is_dataclass(cls):
        fields = _dataclass_fields(cls)
        if fields:
            out.append(fields)
    for _, name, raw in _class_members(cls):
        if isinstance(raw, property):
            doc = _own_docstring(raw.fget) or ""
            out.append(f"##### `{cls.__name__}.{name}`\n")
            annotation = inspect.signature(raw.fget).return_annotation
            kind = f"property {name}"
            if annotation is not inspect.Signature.empty:
                kind += ": " + _format_annotation(annotation)
            out.append(_code(kind))
            out.append(doc + "\n")
            continue
        function = raw.__func__ if isinstance(raw, (staticmethod, classmethod)) else raw
        decorator = "@staticmethod\n" if isinstance(raw, staticmethod) else ""
        decorator = "@classmethod\n" if isinstance(raw, classmethod) else decorator
        skip_first = not isinstance(raw, staticmethod)
        out.append(f"##### `{cls.__name__}.{name}`\n")
        out.append(_code(decorator + format_signature(name, function, skip_first=skip_first)))
        out.append((_own_docstring(function) or "") + "\n")
    return "\n".join(part.rstrip("\n") + "\n" for part in out if part.strip())


def render_module(module_name: str) -> str:
    """Render the API reference of one module."""
    try:
        module = importlib.import_module(module_name)
    except ImportError as exc:
        raise DocsSyncError(f"cannot import {module_name}: {exc}") from exc

    out = [f"### `{module_name}`\n"]
    module_doc = _own_docstring(module)
    if module_doc:
        out.append(module_doc + "\n")

    members = []
    for name, value in vars(module).items():
        if name.startswith("_") or getattr(value, "__module__", None) != module_name:
            continue
        if not (inspect.isclass(value) or inspect.isfunction(value)):
            continue
        if _own_docstring(value) is None:
            continue
        members.append((_source_line(value), name, value))

    for _, name, value in sorted(members, key=lambda item: (item[0], item[1])):
        if inspect.isclass(value):
            out.append(render_class(value))
        else:
            out.append(f"#### `{name}`\n")
            out.append(_code(format_signature(name, value)))
            out.append((_own_docstring(value) or "") + "\n")
    return "\n".join(part.rstrip("\n") + "\n" for part in out if part.strip())


# ---------------------------------------------------------------------------
# Files


def sync_text(root: Path, text: str) -> str:
    """Return the Markdown text with every generated section regenerated."""

    def replace(match: re.Match[str]) -> str:
        kind = match.group("kind")
        argument = match.group("arg").strip()
        body = render_snippet(root, argument) if kind == "snippet" else render_module(argument)
        return match.group("open") + body + match.group("close")

    return MARKER.sub(replace, text)


def markdown_files(root: Path) -> list[Path]:
    """Markdown files that may contain generated sections."""
    files = sorted((root / "docs").rglob("*.md"))
    readme = root / "README.md"
    return [readme, *files] if readme.is_file() else files


def stale_files(root: Path) -> list[Path]:
    """Files whose generated sections differ from what the code produces now."""
    return [
        path
        for path in markdown_files(root)
        if sync_text(root, path.read_text(encoding="utf-8")) != path.read_text(encoding="utf-8")
    ]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--check", action="store_true", help="report stale sections instead of rewriting them")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    sys.path.insert(0, str(root / "src"))

    try:
        if args.check:
            stale = stale_files(root)
            for path in stale:
                print(f"stale generated documentation: {path.relative_to(root)}", file=sys.stderr)
            if stale:
                print("run: uv run python tools/docs_sync.py", file=sys.stderr)
            return 1 if stale else 0
        changed = 0
        for path in markdown_files(root):
            text = path.read_text(encoding="utf-8")
            new = sync_text(root, text)
            if new != text:
                path.write_text(new, encoding="utf-8")
                changed += 1
                print(f"updated {path.relative_to(root)}")
        print(f"{changed} file(s) updated")
        return 0
    except DocsSyncError as exc:
        print(f"docs_sync: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
